<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.0.1-alpha3</Version>
    <PackageVersion>0.0.1-alpha3</PackageVersion>
    <PackageId>Skyline.DataMiner.CICD.Tools.AKA.Lib</PackageId>
    <Authors>SkylineCommunications</Authors>
    <Company>Skyline Communications</Company>
    <Description>Library for creating and managing DataMiner aka short links.</Description>
    <PackageTags>Skyline;DataMiner;aka;url-shortener</PackageTags>
    <PackageProjectUrl>https://skyline.be</PackageProjectUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageIcon>Icon.png</PackageIcon>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Skyline.DataMiner.CICD.Tools.AKA\LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="..\Skyline.DataMiner.CICD.Tools.AKA\nuget\Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
